# 4. Ensembles de Arboles de Decision

Un arbol de decisión es un modelo débil, el aumento del poder predictivo proviene al ensamblar varios arboles de decisión.
<br> Si promedio n arboles identicos, el resultados es exactamente el mismo que utilizar un solo arbol, necesito PERTURBAR cada arbol para disponer de variablidad

la variabilidad provendrá de estas fuentes:


*   Perturbar el dataset
*   Perturbar el algoritmo del arbol
*   Perturbar el dataset y el algoritmo del arbol al mismo tiempo

Se verán estos tres algoritmos


*   Arboles Azarosos
*   Random Forest
*   Gradient Boosting of Decision Trees

#### 4.01 Seteo del ambiente en Google Colab

Esta parte se debe correr con el runtime en Python3
<br>Ir al menu, Runtime -> Change Runtime Type -> Runtime type ->  **Python 3**

Conectar la virtual machine donde esta corriendo Google Colab con el  Google Drive, para poder tener persistencia de archivos

In [1]:
# primero establecer el Runtime de Python 3
from google.colab import drive
drive.mount('/content/.drive')

Drive already mounted at /content/.drive; to attempt to forcibly remount, call drive.mount("/content/.drive", force_remount=True).

Para correr la siguiente celda es fundamental en Arranque en Frio haber copiado el archivo kaggle.json al Google Drive, en la carpeta indicada en el instructivo

<br>los siguientes comando estan en shell script de Linux
*   Crear las carpetas en el Google Drive
*   "instalar" el archivo kaggle.json desde el Google Drive a la virtual machine para que pueda ser utilizado por la libreria  kaggle de Python
*   Bajar el  **dataset_pequeno**  al  Google Drive  y tambien al disco local de la virtual machine que esta corriendo Google Colab

In [2]:
%%shell

mkdir -p "/content/.drive/My Drive/dmeyf"
mkdir -p "/content/buckets"
ln -sfn "/content/.drive/My Drive/dmeyf"   /content/buckets/b1

mkdir -p ~/.kaggle
cp /content/buckets/b1/kaggle/kaggle.json  ~/.kaggle
chmod 600 ~/.kaggle/kaggle.json


mkdir -p /content/buckets/b1/exp
mkdir -p /content/buckets/b1/datasets
mkdir -p /content/datasets


# defino funcion descargar()
descargar() {
  carpeta_destino="/content/buckets/b1/datasets/"
  url_origen="https://storage.googleapis.com/open-courses/utn2026-b40a/"
  archivo="$1"

  if ! test -f "$carpeta_destino""$archivo"; then
    wget  "$url_origen""$archivo"  -O "$carpeta_destino""$archivo"
  fi

  if ! test -f  "/content/datasets/""$archivo"; then
    cp  "$carpeta_destino""$archivo"  "/content/datasets/""$archivo"
  fi;
}

# hago la descarga efectiva, llamando a descargar()
descargar  "dataset_pequeno.csv"



---

## 4.02 Arboles Azarosos

Arboles Azarosos es el nombre de un algoritmo trivial (por favor NO confundir con Random Forest)
Qué tipo de perturbaciones se realizan en Arboles Azarosos
* Se perturba el dataset
* No se perturba el algoritmo, es siempre rpart original

Cada  arbolito de  Arboles Azarosos se entrena sobre un dataset perturbado,  que tiene exactamente la misma cantidad de registros pero solo un subconjunto de los atributos (campos)  del dataset, tomados al azar, de los originales.
<br> En esta primera corrida, se construira cada arbol en un dataset utilizando el 50% de los campos

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Mon Aug 24 04:12:55 AM 2026"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  671287 35.9 1473300    78.7 1473300  78.7
Vcells 1242646  9.5 8388608    64.0 1978712  15.1

In [3]:
# cargo las librerias que necesito
require("data.table")
require("rpart")

Loading required package: data.table


Attaching package: ‘data.table’


The following object is masked from ‘package:base’:

    %notin%


Loading required package: rpart

Aqui debe cargar SU semilla primigenia

In [4]:
"""
PARAM <- list()
PARAM$semilla_primigenia <- 378089

# parametros  arbol
# entreno cada arbol con solo 50% de las variables variables
#  por ahora, es fijo
PARAM$feature_fraction <- 0.5

PARAM$rpart$cp <- -1
PARAM$rpart$minsplit <- 500
PARAM$rpart$minbucket <- 180
PARAM$rpart$maxdepth <- 7

# voy a generar 512 arboles,
#  a mas arboles mas tiempo de proceso y MEJOR MODELO,
#  pero ganancias marginales
PARAM$num_trees_max <- 512
"""

ERROR: Error in parse(text = input): <text>:1:3: unexpected string constant
18: PARAM$num_trees_max <- 512
19: "
      ^

In [20]:
# nueva celda

PARAM <- list()
PARAM$semilla_primigenia <- 378089

# PAra identificar corrida con nueva grilla
PARAM$tag_experimento <- "colab_v2"
PARAM$competencia <- "utn-2026-inicial"

# ahora son rangos a explorar, no valores fijos
PARAM$rango_feature_fraction <- c(0.5 )
PARAM$rango_minsplit         <- c(200,400, 500, 600, 700)
PARAM$rango_minbucket        <- c(50,100, 150, 175)
PARAM$rango_maxdepth         <- c(10, 12, 14)

PARAM$cp_fijo <- -1   # se mantiene fijo, no se itera

# voy a generar 32 arboles por cada combinacion de hiperparametros
PARAM$num_trees_max <- 32

In [21]:
# carpeta de trabajo
setwd("/content/buckets/b1/exp")
experimento <- "exp420_32_g2"     # <<< carpeta nueva
dir.create(experimento, showWarnings = FALSE)
setwd(paste0("/content/buckets/b1/exp/", experimento))

PARAM$tag_experimento <- "colab_v2"   # el tag sigue siendo importante para el analisis despues

In [7]:
# lectura del dataset
dataset <- fread("/content/datasets/dataset_pequeno.csv")

In [8]:
# defino los dataset de entrenamiento y aplicacion
dtrain <- dataset[foto_mes == 202107]
dfuture <- dataset[foto_mes == 202109]

# arreglo clase_ternaria por algun distraido ""
dfuture[, clase_ternaria := NA ]

In [9]:
# Establezco cuales son los campos que puedo usar para la prediccion
# el copy() es por la Lazy Evaluation
campos_buenos <- copy(setdiff(colnames(dtrain), c("clase_ternaria")))

In [10]:
# que tamanos de ensemble grabo a disco
# grabar <- c(1, 2, 4, 8, 16, 32, 64, 128, 256, 384, 512)

In [11]:
# tb_prediccion <- dfuture[, list(numero_de_cliente)]
# aqui se va acumulando la probabilidad del ensemble
# tb_prediccion[, prob_acumulada := 0]

In [12]:
# set.seed(PARAM$semilla_primigenia) # Establezco la semilla aleatoria

In [13]:
"""
for (arbolito in seq(PARAM$num_trees_max) ) {
  message( arbolito, " ")
  qty_campos_a_utilizar <- as.integer(length(campos_buenos)
    * PARAM$feature_fraction)

  # elijo los campos al azar
  campos_random <- sample(campos_buenos, qty_campos_a_utilizar)

  # paso de un vector a un string con los elementos
  # separados por un signo de "+"
  # este hace falta para la formula
  campos_random <- paste(campos_random, collapse= " + ")

  # armo la formula para rpart
  formulita <- paste0("clase_ternaria ~ ", campos_random)

  # genero el arbol de decision
  modelo <- rpart(formulita,
    data= dtrain,
    xval= 0,
    control= PARAM$rpart
  )

  # aplico el modelo a los datos que no tienen clase
  prediccion <- predict(modelo, dfuture, type= "prob")

  tb_prediccion[, prob_acumulada := prob_acumulada + prediccion[, "BAJA+2"]]

  if (arbolito %in% grabar) {
    umbral_corte <- (1 / 40) * arbolito
    tb_prediccion[, Predicted := as.numeric(prob_acumulada > umbral_corte)]

    archivo_kaggle <- paste0(
        "KA420_",
        sprintf("%.3d", arbolito), # para que tenga ceros adelante
        ".csv"
      )

    # grabo el archivo
    fwrite( tb_prediccion[, list(numero_de_cliente, Predicted)],
      file= archivo_kaggle,
      sep= ","
    )

    # subida a Kaggle
    comando <- "kaggle competitions submit"
    competencia <- "-c utn-2026-inicial"
    arch <- paste( "-f", archivo_kaggle)

    mensaje <- paste0("-m 'cp=", PARAM$rpart$cp, "  minsplit=", PARAM$rpart$minsplit, "  minbucket=", PARAM$rpart$minbucket, " maxdepth=", PARAM$rpart$maxdepth, "'" )
    linea <- paste( comando, competencia, arch, mensaje)
    salida <- system(linea, intern=TRUE)
    cat(salida)
  }
}
"""

ERROR: Error in parse(text = input): <text>:1:3: unexpected string constant
2: for (arbolito in seq(PARAM$num_trees_max) ) {
3:   message( arbolito, "
     ^

In [14]:
# armar la grilla y persistirla
archivo_grilla <- paste0("grilla_hiperparams_", PARAM$tag_experimento, ".RDS")  # <<< nombre distinto

if (file.exists(archivo_grilla)) {

  grilla_hiperparams <- readRDS(archivo_grilla)
  cat("Grilla existente cargada.",
      sum(grilla_hiperparams$estado == "pendiente"), "pendientes de",
      nrow(grilla_hiperparams), "totales.\n")

} else {

  grilla_hiperparams <- CJ(
    feature_fraction = PARAM$rango_feature_fraction,
    minsplit          = PARAM$rango_minsplit,
    minbucket         = PARAM$rango_minbucket,
    maxdepth          = PARAM$rango_maxdepth
  )

  grilla_hiperparams <- grilla_hiperparams[minsplit >= 2 * minbucket]

  grilla_hiperparams[, cp := PARAM$cp_fijo]
  grilla_hiperparams[, id := .I]
  grilla_hiperparams[, tag := PARAM$tag_experimento]
  grilla_hiperparams[, estado := "pendiente"]

  saveRDS(grilla_hiperparams, archivo_grilla)
  cat("Grilla nueva creada con", nrow(grilla_hiperparams), "combinaciones validas.\n")
}

Grilla existente cargada. 54 pendientes de 54 totales.

In [15]:
# función que entrena UN ensemble de 32 árboles
# para UNA combinación de hiperparámetros y sube a Kaggle

generar_y_subir <- function(feature_fraction, vcp, minsplit, minbucket, maxdepth, id_combo, tag) {

  tb_prediccion <- dfuture[, list(numero_de_cliente)]
  tb_prediccion[, prob_acumulada := 0]

  control_arbol <- list(cp = vcp, minsplit = minsplit, minbucket = minbucket, maxdepth = maxdepth)
  set.seed(PARAM$semilla_primigenia)

  for (arbolito in seq(PARAM$num_trees_max)) {
    qty_campos_a_utilizar <- as.integer(length(campos_buenos) * feature_fraction)
    campos_random <- sample(campos_buenos, qty_campos_a_utilizar)
    formulita <- paste0("clase_ternaria ~ ", paste(campos_random, collapse = " + "))

    modelo <- rpart(formulita, data = dtrain, xval = 0, control = control_arbol)
    prediccion <- predict(modelo, dfuture, type = "prob")
    tb_prediccion[, prob_acumulada := prob_acumulada + prediccion[, "BAJA+2"]]
  }

  tb_prediccion[, prob_promedio := prob_acumulada / PARAM$num_trees_max]
  tb_prediccion[, Predicted := as.numeric(prob_promedio > 0.025)]

  # <<< nombre de archivo incluye el tag
  archivo_kaggle <- paste0("KA420_", tag, "_combo", sprintf("%.4d", id_combo), ".csv")

  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)], file = archivo_kaggle, sep = ",")

  # <<< mensaje incluye el tag
  mensaje <- paste0("-m 'tag=", tag,
                     " id=", id_combo,
                     " ff=", feature_fraction,
                     " cp=", vcp,
                     " minsplit=", minsplit,
                     " minbucket=", minbucket,
                     " maxdepth=", maxdepth, "'")

  linea <- paste("kaggle competitions submit -c", PARAM$competencia,
                  "-f", archivo_kaggle, mensaje)
  salida <- system(linea, intern = TRUE)
  cat(salida, "\n")
}

In [16]:
# loop principal
# solo procesa lo "pendiente", guarda checkpoint tras cada submit

pendientes <- which(grilla_hiperparams$estado == "pendiente")

for (i in pendientes) {

  fila <- grilla_hiperparams[i]

  cat("\nCombinacion", fila$id, "(", fila$tag, ") / ", nrow(grilla_hiperparams),
      " | ff=", fila$feature_fraction, " minsplit=", fila$minsplit,
      " minbucket=", fila$minbucket, " maxdepth=", fila$maxdepth, "\n")

  resultado_ok <- tryCatch({
    generar_y_subir(
      feature_fraction = fila$feature_fraction,
      vcp              = fila$cp,
      minsplit         = fila$minsplit,
      minbucket        = fila$minbucket,
      maxdepth         = fila$maxdepth,
      id_combo         = fila$id,
      tag              = fila$tag
    )
    TRUE
  }, error = function(e) {
    cat("  ERROR:", conditionMessage(e), "\n")
    FALSE
  })

  if (resultado_ok) {
    grilla_hiperparams[id == fila$id, estado := "subido"]
    saveRDS(grilla_hiperparams, archivo_grilla)
  } else {
    cat("\n  Cortando el loop.\n")
    break
  }

  Sys.sleep(2)
}

Combinacion 1 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 200  minbucket= 50  maxdepth= 10

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0001.csv -m 'tag=colab_v2 id=1 ff=0.5 cp=-1 minsplit=200 minbucket=50 maxdepth=10'' had status 2”

Combinacion 2 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 200  minbucket= 50  maxdepth= 12

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0002.csv -m 'tag=colab_v2 id=2 ff=0.5 cp=-1 minsplit=200 minbucket=50 maxdepth=12'' had status 2”

Combinacion 3 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 200  minbucket= 50  maxdepth= 14

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0003.csv -m 'tag=colab_v2 id=3 ff=0.5 cp=-1 minsplit=200 minbucket=50 maxdepth=14'' had status 2”

Combinacion 4 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 200  minbucket= 100  maxdepth= 10

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0004.csv -m 'tag=colab_v2 id=4 ff=0.5 cp=-1 minsplit=200 minbucket=100 maxdepth=10'' had status 2”

Combinacion 5 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 200  minbucket= 100  maxdepth= 12

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0005.csv -m 'tag=colab_v2 id=5 ff=0.5 cp=-1 minsplit=200 minbucket=100 maxdepth=12'' had status 2”

Combinacion 6 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 200  minbucket= 100  maxdepth= 14

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0006.csv -m 'tag=colab_v2 id=6 ff=0.5 cp=-1 minsplit=200 minbucket=100 maxdepth=14'' had status 2”

Combinacion 7 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 400  minbucket= 50  maxdepth= 10

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0007.csv -m 'tag=colab_v2 id=7 ff=0.5 cp=-1 minsplit=400 minbucket=50 maxdepth=10'' had status 2”

Combinacion 8 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 400  minbucket= 50  maxdepth= 12

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0008.csv -m 'tag=colab_v2 id=8 ff=0.5 cp=-1 minsplit=400 minbucket=50 maxdepth=12'' had status 2”

Combinacion 9 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 400  minbucket= 50  maxdepth= 14

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0009.csv -m 'tag=colab_v2 id=9 ff=0.5 cp=-1 minsplit=400 minbucket=50 maxdepth=14'' had status 2”

Combinacion 10 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 400  minbucket= 100  maxdepth= 10

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0010.csv -m 'tag=colab_v2 id=10 ff=0.5 cp=-1 minsplit=400 minbucket=100 maxdepth=10'' had status 2”

Combinacion 11 ( colab_v2 ) /  54  | ff= 0.5  minsplit= 400  minbucket= 100  maxdepth= 12

Warning message in system(linea, intern = TRUE):
“running command 'kaggle competitions submit -c  -f KA420_colab_v2_combo0011.csv -m 'tag=colab_v2 id=11 ff=0.5 cp=-1 minsplit=400 minbucket=100 maxdepth=12'' had status 2”

In [ ]:
# función que entrena UN ensemble de 32 árboles
# para UNA combinación de hiperparámetros y sube a Kaggle

generar_y_subir <- function(feature_fraction, vcp, minsplit, minbucket, maxdepth, id_combo, tag) {

  tb_prediccion <- dfuture[, list(numero_de_cliente)]
  tb_prediccion[, prob_acumulada := 0]

  control_arbol <- list(cp = vcp, minsplit = minsplit, minbucket = minbucket, maxdepth = maxdepth)
  set.seed(PARAM$semilla_primigenia)

  for (arbolito in seq(PARAM$num_trees_max)) {
    qty_campos_a_utilizar <- as.integer(length(campos_buenos) * feature_fraction)
    campos_random <- sample(campos_buenos, qty_campos_a_utilizar)
    formulita <- paste0("clase_ternaria ~ ", paste(campos_random, collapse = " + "))

    modelo <- rpart(formulita, data = dtrain, xval = 0, control = control_arbol)
    prediccion <- predict(modelo, dfuture, type = "prob")
    tb_prediccion[, prob_acumulada := prob_acumulada + prediccion[, "BAJA+2"]]
  }

  tb_prediccion[, prob_promedio := prob_acumulada / PARAM$num_trees_max]
  tb_prediccion[, Predicted := as.numeric(prob_promedio > 0.025)]

  archivo_kaggle <- paste0("KA420_", tag, "_combo", sprintf("%.4d", id_combo), ".csv")
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)], file = archivo_kaggle, sep = ",")

  mensaje <- paste0("-m 'tag=", tag,
                     " id=", id_combo,
                     " ff=", feature_fraction,
                     " cp=", vcp,
                     " minsplit=", minsplit,
                     " minbucket=", minbucket,
                     " maxdepth=", maxdepth, "'")

  linea <- paste("kaggle competitions submit -c", PARAM$competencia,
                  "-f", archivo_kaggle, mensaje)

  salida <- system(linea, intern = TRUE)
  status <- attr(salida, "status")
  cat(salida, "\n")

  # <<< NUEVO: si el comando fallo, lanzo un error real para que el tryCatch lo capture
  if (!is.null(status) && status != 0) {
    stop(paste("Fallo el submit a Kaggle (status", status, "):", paste(salida, collapse = " ")))
  }
}

In [ ]:
# función que entrena UN ensemble de 32 árboles
# para UNA combinación de hiperparámetros y sube a Kaggle

generar_y_subir <- function(feature_fraction, vcp, minsplit, minbucket, maxdepth, id_combo, tag) {

  tb_prediccion <- dfuture[, list(numero_de_cliente)]
  tb_prediccion[, prob_acumulada := 0]

  control_arbol <- list(cp = vcp, minsplit = minsplit, minbucket = minbucket, maxdepth = maxdepth)
  set.seed(PARAM$semilla_primigenia)

  for (arbolito in seq(PARAM$num_trees_max)) {
    qty_campos_a_utilizar <- as.integer(length(campos_buenos) * feature_fraction)
    campos_random <- sample(campos_buenos, qty_campos_a_utilizar)
    formulita <- paste0("clase_ternaria ~ ", paste(campos_random, collapse = " + "))

    modelo <- rpart(formulita, data = dtrain, xval = 0, control = control_arbol)
    prediccion <- predict(modelo, dfuture, type = "prob")
    tb_prediccion[, prob_acumulada := prob_acumulada + prediccion[, "BAJA+2"]]
  }

  tb_prediccion[, prob_promedio := prob_acumulada / PARAM$num_trees_max]
  tb_prediccion[, Predicted := as.numeric(prob_promedio > 0.025)]

  # <<< nombre de archivo incluye el tag
  archivo_kaggle <- paste0("KA420_", tag, "_combo", sprintf("%.4d", id_combo), ".csv")

  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)], file = archivo_kaggle, sep = ",")

  # <<< mensaje incluye el tag
  mensaje <- paste0("-m 'tag=", tag,
                     " id=", id_combo,
                     " ff=", feature_fraction,
                     " cp=", vcp,
                     " minsplit=", minsplit,
                     " minbucket=", minbucket,
                     " maxdepth=", maxdepth, "'")

  linea <- paste("kaggle competitions submit -c", PARAM$competencia,
                  "-f", archivo_kaggle, mensaje)
  salida <- system(linea, intern = TRUE)
  cat(salida, "\n")
}

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

# Subir los csv generados y no subidos

In [30]:
archivos_generados <- list.files(pattern = "KA420_colab_v2_combo[0-9]+\\.csv")
ids_con_csv <- as.integer(gsub(".*combo([0-9]+)\\.csv", "\\1", archivos_generados))

cat("CSVs ya generados en disco:", length(ids_con_csv), "\n")
print(sort(ids_con_csv))

pendientes_con_csv <- grilla_hiperparams[id %in% ids_con_csv & estado == "pendiente"]
cat("De esos, pendientes de subir:", nrow(pendientes_con_csv), "\n")

for (i in seq_len(nrow(pendientes_con_csv))) {
  fila <- pendientes_con_csv[i]

  archivo_kaggle <- paste0("KA420_", fila$tag, "_combo", sprintf("%.4d", fila$id), ".csv")

  mensaje <- paste0("-m 'tag=", fila$tag,
                     " id=", fila$id,
                     " ff=", fila$feature_fraction,
                     " cp=", fila$cp,
                     " minsplit=", fila$minsplit,
                     " minbucket=", fila$minbucket,
                     " maxdepth=", fila$maxdepth, "'")

  linea <- paste("kaggle competitions submit -c", PARAM$competencia,
                  "-f", archivo_kaggle, mensaje)

  salida <- system(linea, intern = TRUE)
  status <- attr(salida, "status")
  cat(salida, "\n")

  if (is.null(status) || status == 0) {
    grilla_hiperparams[id == fila$id, estado := "subido"]
    saveRDS(grilla_hiperparams, archivo_grilla)
    cat("  -> OK, id", fila$id, "subido\n")
  } else {
    cat("  -> FALLO id", fila$id, ", deteniendo\n")
    break
  }

  Sys.sleep(2)
}

table(grilla_hiperparams$estado)

CSVs ya generados en disco: 11
 [1]  1  2  3  4  5  6  7  8  9 10 11
De esos, pendientes de subir: 11
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 1 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 2 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 3 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 4 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 5 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 6 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 7 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 8 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 9 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 10 subido
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2) Successfully submitted to UTN 2026 Inicial
  -> OK, id 11 subido

pendiente    subido
       43        11

In [24]:
# reviso que dice la grilla actualmente
table(grilla_hiperparams$estado)
print(grilla_hiperparams[id %in% 1:15])

pendiente    subido
       43        11

Key: <feature_fraction, minsplit, minbucket, maxdepth>
    feature_fraction minsplit minbucket maxdepth    id      tag    estado    cp
               <num>    <num>     <num>    <num> <int>   <char>    <char> <num>
 1:              0.5      200        50       10     1 colab_v2    subido    -1
 2:              0.5      200        50       12     2 colab_v2    subido    -1
 3:              0.5      200        50       14     3 colab_v2    subido    -1
 4:              0.5      200       100       10     4 colab_v2    subido    -1
 5:              0.5      200       100       12     5 colab_v2    subido    -1
 6:              0.5      200       100       14     6 colab_v2    subido    -1
 7:              0.5      400        50       10     7 colab_v2    subido    -1
 8:              0.5      400        50       12     8 colab_v2    subido    -1
 9:              0.5      400        50       14     9 colab_v2    subido    -1
10:              0.5      400       100       10    10 colab_v2    subido    -1
11:              0.5      400       100       12    11 colab_v2    subido    -1
12:              0.5      400       100       14    12 colab_v2 pendiente    -1
13:              0.5      400       150       10    13 colab_v2 pendiente    -1
14:              0.5      400       150       12    14 colab_v2 pendiente    -1
15:              0.5      400       150       14    15 colab_v2 pendiente    -1

In [25]:
cat("PARAM$competencia: '", PARAM$competencia, "'\n", sep="")

PARAM$competencia: 'utn-2026-inicial'

In [26]:
raw <- system("kaggle competitions submissions -c utn-2026-inicial -v --page-size 200", intern = TRUE)
raw <- raw[!grepl("^Warning", raw)]
subs_check <- fread(paste(raw, collapse = "\n"), header = TRUE, fill = TRUE)

# busco si aparece ALGUNA combinacion de colab_v2 en el historial real
subs_check[grepl("colab_v2", fileName)]

     fileName date description status publicScore privateScore

In [27]:
# si el chequeo anterior confirmo que NO hay ninguna colab_v2 en Kaggle:
grilla_hiperparams[id %in% 1:11, estado := "pendiente"]
saveRDS(grilla_hiperparams, archivo_grilla)

table(grilla_hiperparams$estado)

pendiente
       54

In [29]:
grilla_hiperparams[id %in% 1:11, estado := "pendiente"]
saveRDS(grilla_hiperparams, archivo_grilla)

table(grilla_hiperparams$estado)

pendiente
       54

# Extraccion de datos de KAGGLE

In [ ]:
nombre_competencia <- "utn-2026-inicial"   # confirmá que este es el nombre exacto de tu competencia

submissions_raw <- system(
  paste0("kaggle competitions submissions -c ", nombre_competencia, " -v"),
  intern = TRUE
)

submissions <- fread(paste(submissions_raw, collapse = "\n"))
print(names(submissions))
head(submissions)

Warning message in fread(paste(submissions_raw, collapse = "\n")):
“Discarded single-line footer: <<KA420_320014.csv,2026-08-23 10:59:23.483000,id=14 ff=0.3 cp=-1 minsplit=500 minbucket=100 maxdepth=7,SubmissionStatus.COMPLETE,341.415,>>”

[1] "fileName"     "date"         "description"  "status"       "publicScore"
[6] "privateScore"

  fileName            date
1 KA420_combo0063.csv 2026-08-24 02:37:54
2 KA420_combo0062.csv 2026-08-24 02:23:38
3 KA420_320061.csv    2026-08-24 02:04:03
4 KA420_320060.csv    2026-08-24 01:41:43
5 KA420_320059.csv    2026-08-24 01:10:56
6 KA420_320058.csv    2026-08-24 00:44:30
  description
1 id=63 ff=0.5 cp=-1 minsplit=500 minbucket=100 maxdepth=8
2 id=62 ff=0.5 cp=-1 minsplit=500 minbucket=100 maxdepth=7
3 id=61 ff=0.5 cp=-1 minsplit=500 minbucket=100 maxdepth=6
4 id=60 ff=0.5 cp=-1 minsplit=400 minbucket=200 maxdepth=8
5 id=59 ff=0.5 cp=-1 minsplit=400 minbucket=200 maxdepth=7
6 id=58 ff=0.5 cp=-1 minsplit=400 minbucket=200 maxdepth=6
  status                    publicScore privateScore
1 SubmissionStatus.COMPLETE 357.081
2 SubmissionStatus.COMPLETE 351.831
3 SubmissionStatus.COMPLETE 351.415
4 SubmissionStatus.COMPLETE 345.581
5 SubmissionStatus.COMPLETE 342.581
6 SubmissionStatus.COMPLETE 348.165

In [ ]:
nrow(submissions)
print(submissions)

[1] 49

               fileName                date
                 <char>              <POSc>
 1: KA420_combo0063.csv 2026-08-24 02:37:54
 2: KA420_combo0062.csv 2026-08-24 02:23:38
 3:    KA420_320061.csv 2026-08-24 02:04:03
 4:    KA420_320060.csv 2026-08-24 01:41:43
 5:    KA420_320059.csv 2026-08-24 01:10:56
 6:    KA420_320058.csv 2026-08-24 00:44:30
 7:    KA420_320057.csv 2026-08-24 00:22:21
 8:    KA420_320056.csv 2026-08-23 23:53:00
 9:    KA420_320055.csv 2026-08-23 23:27:25
10:    KA420_320054.csv 2026-08-23 23:05:36
11:    KA420_320053.csv 2026-08-23 22:36:01
12:    KA420_320052.csv 2026-08-23 22:10:10
13:    KA420_320051.csv 2026-08-23 21:48:35
14:    KA420_320050.csv 2026-08-23 21:19:43
15:    KA420_320049.csv 2026-08-23 20:54:28
16:    KA420_320048.csv 2026-08-23 20:32:51
17:    KA420_320047.csv 2026-08-23 20:15:12
18:    KA420_320046.csv 2026-08-23 19:59:27
19:    KA420_320045.csv 2026-08-23 19:46:02
20:    KA420_320044.csv 2026-08-23 19:01:07
21:    KA420_320043.csv 2026-08-23 18:44:47
22:    KA420_320042.csv 2026-08-23 18:31:01
23:    KA420_320041.csv 2026-08-23 18:12:28
24:    KA420_320040.csv 2026-08-23 17:56:21
25:    KA420_320039.csv 2026-08-23 17:42:39
26:    KA420_320038.csv 2026-08-23 17:24:14
27:    KA420_320037.csv 2026-08-23 17:08:05
28:    KA420_320036.csv 2026-08-23 16:54:24
29:    KA420_320035.csv 2026-08-23 16:36:02
30:    KA420_320034.csv 2026-08-23 16:19:55
31:    KA420_320033.csv 2026-08-23 16:06:10
32:    KA420_320032.csv 2026-08-23 15:47:37
33:    KA420_320031.csv 2026-08-23 15:31:30
34:    KA420_320030.csv 2026-08-23 15:17:46
35:    KA420_320029.csv 2026-08-23 14:59:21
36:    KA420_320028.csv 2026-08-23 14:43:24
37:    KA420_320027.csv 2026-08-23 14:29:51
38:    KA420_320026.csv 2026-08-23 14:11:26
39:    KA420_320025.csv 2026-08-23 13:55:23
40:    KA420_320024.csv 2026-08-23 13:41:41
41:    KA420_320023.csv 2026-08-23 13:23:13
42:    KA420_320022.csv 2026-08-23 13:07:13
43:    KA420_320021.csv 2026-08-23 12:53:33
44:    KA420_320020.csv 2026-08-23 12:35:02
45:    KA420_320019.csv 2026-08-23 12:18:58
46:    KA420_320018.csv 2026-08-23 12:05:23
47:    KA420_320017.csv 2026-08-23 11:47:07
48:    KA420_320016.csv 2026-08-23 11:31:11
49:    KA420_320015.csv 2026-08-23 11:17:35
               fileName                date
                 <char>              <POSc>
                                                 description
                                                      <char>
 1: id=63 ff=0.5 cp=-1 minsplit=500 minbucket=100 maxdepth=8
 2: id=62 ff=0.5 cp=-1 minsplit=500 minbucket=100 maxdepth=7
 3: id=61 ff=0.5 cp=-1 minsplit=500 minbucket=100 maxdepth=6
 4: id=60 ff=0.5 cp=-1 minsplit=400 minbucket=200 maxdepth=8
 5: id=59 ff=0.5 cp=-1 minsplit=400 minbucket=200 maxdepth=7
 6: id=58 ff=0.5 cp=-1 minsplit=400 minbucket=200 maxdepth=6
 7: id=57 ff=0.5 cp=-1 minsplit=400 minbucket=175 maxdepth=8
 8: id=56 ff=0.5 cp=-1 minsplit=400 minbucket=175 maxdepth=7
 9: id=55 ff=0.5 cp=-1 minsplit=400 minbucket=175 maxdepth=6
10: id=54 ff=0.5 cp=-1 minsplit=400 minbucket=150 maxdepth=8
11: id=53 ff=0.5 cp=-1 minsplit=400 minbucket=150 maxdepth=7
12: id=52 ff=0.5 cp=-1 minsplit=400 minbucket=150 maxdepth=6
13: id=51 ff=0.5 cp=-1 minsplit=400 minbucket=100 maxdepth=8
14: id=50 ff=0.5 cp=-1 minsplit=400 minbucket=100 maxdepth=7
15: id=49 ff=0.5 cp=-1 minsplit=400 minbucket=100 maxdepth=6
16: id=48 ff=0.3 cp=-1 minsplit=700 minbucket=200 maxdepth=8
17: id=47 ff=0.3 cp=-1 minsplit=700 minbucket=200 maxdepth=7
18: id=46 ff=0.3 cp=-1 minsplit=700 minbucket=200 maxdepth=6
19: id=45 ff=0.3 cp=-1 minsplit=700 minbucket=175 maxdepth=8
20: id=44 ff=0.3 cp=-1 minsplit=700 minbucket=175 maxdepth=7
21: id=43 ff=0.3 cp=-1 minsplit=700 minbucket=175 maxdepth=6
22: id=42 ff=0.3 cp=-1 minsplit=700 minbucket=150 maxdepth=8
23: id=41 ff=0.3 cp=-1 minsplit=700 minbucket=150 maxdepth=7
24: id=40 ff=0.3 cp=-1 minsplit=700 minbucket=150 maxdepth=6
25: id=39 ff=0.3 cp=-1 minsplit=700 minbucket=100 maxdepth=8
26: id=38 ff=0.3 cp=-1 minsplit=700 minbucket=100 maxdepth=7
27: id=37 ff=0.3 cp=-1 minsplit=700 minbucket=100 maxdepth=6
28: id=36 ff=0.3 cp=-1 minsplit=600 minbucket=200 maxdepth=8
29: id=35 ff=0.3 cp=-1 minsplit=600 minbucket=200 maxdepth=7
30: id=34 ff=0.3 cp=-1 minsplit=600 minbucket=200 maxdepth=6
31: id=33 ff=0.3 cp=-1 minsplit=600 minbucket=175 maxdepth=8
32: id=32 ff=0.3 cp=-1 minsplit=600 minbucket=175 maxdepth=7
33: id=31 ff=0.3 cp=-1 minsplit=600 minbucket=175 maxdepth=6
34: id=30 ff=0.3 cp=-1 minsplit=600 minbucket=150 maxdepth=8
35: id=29 ff=0.3 cp=-1 minsplit=600 minbucket=150 maxdepth=7
36: id=28 ff=0.3 cp=-1 minsplit=600 minbucket=150 maxdepth=6
37: id=27 ff=0.3 cp=-1 minsplit=600 minbucket=100 maxdepth=8
38: id=26 ff=0.3 cp=-1 minsplit=600 minbucket=100 maxdepth=7
39: id=25 ff=0.3 cp=-1 minsplit=600 minbucket=100 maxdepth=6
40: id=24 ff=0.3 cp=-1 minsplit=500 minbucket=200 maxdepth=8
41: id=23 ff=0.3 cp=-1 minsplit=500 minbucket=200 maxdepth=7
42: id=22 ff=0.3 cp=-1 minsplit=500 minbucket=200 maxdepth=6
43: id=21 ff=0.3 cp=-1 minsplit=500 minbucket=175 maxdepth=8
44: id=20 ff=0.3 cp=-1 minsplit=500 minbucket=175 maxdepth=7
45: id=19 ff=0.3 cp=-1 minsplit=500 minbucket=175 maxdepth=6
46: id=18 ff=0.3 cp=-1 minsplit=500 minbucket=150 maxdepth=8
47: id=17 ff=0.3 cp=-1 minsplit=500 minbucket=150 maxdepth=7
48: id=16 ff=0.3 cp=-1 minsplit=500 minbucket=150 maxdepth=6
49: id=15 ff=0.3 cp=-1 minsplit=500 minbucket=100 maxdepth=8
                                                 description
                                                      <char>
                       status publicScore privateScore
                       <char>       <num>       <char>
 1: SubmissionStatus.COMPLETE     357.081
 2: SubmissionStatus.COMPLETE     351.831
 3: SubmissionStatus.COMPLETE     351.415
 4: SubmissionStatus.COMPLETE     345.581
 5: SubmissionStatus.COMPLETE     342.581
 6: SubmissionStatus.COMPLETE     348.165
 7: SubmissionStatus.COMPLETE     336.331
 8: SubmissionStatus.COMPLETE     340.748
 9: SubmissionStatus.COMPLETE     345.498
10: SubmissionStatus.COMPLETE     337.415
11: SubmissionStatus.COMPLETE     340.081
12: SubmissionStatus.COMPLETE     344.331
13: SubmissionStatus.COMPLETE     353.081
14: SubmissionStatus.COMPLETE     353.331
15: SubmissionStatus.COMPLETE     352.165
16: SubmissionStatus.COMPLETE     334.998
17: SubmissionStatus.COMPLETE     336.665
18: SubmissionStatus.COMPLETE     333.665
19: SubmissionStatus.COMPLETE     349.915
20: SubmissionStatus.COMPLETE     336.831
21: SubmissionStatus.COMPLETE     334.331
22: SubmissionStatus.COMPLETE     339.665
23: SubmissionStatus.COMPLETE     334.581
24: SubmissionStatus.COMPLETE     332.581
25: SubmissionStatus.COMPLETE     341.665
26: SubmissionStatus.COMPLETE     338.915
27: SubmissionStatus.COMPLETE     337.331
28: SubmissionStatus.COMPLETE     339.498
29: SubmissionStatus.COMPLETE     330.748
30: SubmissionStatus.COMPLETE     331.581
31: SubmissionStatus.COMPLETE     336.331
32: SubmissionStatus.COMPLETE     328.165
33: SubmissionStatus.COMPLETE     332.498
34: SubmissionStatus.COMPLETE     336.665
35: SubmissionStatus.COMPLETE     335.831
36: SubmissionStatus.COMPLETE     326.998
37: SubmissionStatus.COMPLETE     343.165
38: SubmissionStatus.COMPLETE     340.665
39: SubmissionStatus.COMPLETE     335.581
40: SubmissionStatus.COMPLETE     340.248
41: SubmissionStatus.COMPLETE     333.998
42: SubmissionStatus.COMPLETE     331.581
43: SubmissionStatus.COMPLETE     336.665
44: SubmissionStatus.COMPLETE     338.498
45: SubmissionStatus.COMPLETE     332.581
46: SubmissionStatus.COMPLETE     334.248
47: SubmissionStatus.COMPLETE     336.498
48: SubmissionStatus.COMPLETE     327.165
49: SubmissionStatus.COMPLETE     340.331
                       status publicScore privateScore
                       <char>       <num>       <char>

In [ ]:
help_output <- system("kaggle competitions submissions --help", intern = TRUE)
cat(help_output, sep = "\n")

usage: kaggle competitions submissions [-h] [-v] [-q] [--page-size PAGE_SIZE]
                                       [--page-token PAGE_TOKEN]
                                       [competition]

options:
  -h, --help            show this help message and exit
  competition           Competition URL suffix (use "kaggle competitions list" to show options)
                        If empty, the default competition will be used (use "kaggle config set competition")"
  -v, --csv             Print results in CSV format (if not set print in table format)
  -q, --quiet           Suppress printing information about the upload/download progress
  --page-size PAGE_SIZE
                        Number of items to show on a page. Default size is 20, max is 200
  --page-token PAGE_TOKEN
                        Page token for results paging.

In [ ]:
submissions_raw <- system(
  paste0("kaggle competitions submissions -c ", nombre_competencia, " -v --page-size 200"),
  intern = TRUE
)

submissions <- fread(paste(submissions_raw, collapse = "\n"), header = TRUE, fill = TRUE)
nrow(submissions)

[1] 83

In [ ]:
submissions_raw <- system(
  paste0("kaggle competitions submissions -c ", nombre_competencia, " -v --page-size 200"),
  intern = TRUE
)

# saco cualquier linea que sea un warning, no datos reales
submissions_raw <- submissions_raw[!grepl("^Warning", submissions_raw)]

submissions <- fread(paste(submissions_raw, collapse = "\n"), header = TRUE, fill = TRUE)
print(names(submissions))
nrow(submissions)

[1] "fileName"     "date"         "description"  "status"       "publicScore"
[6] "privateScore"

[1] 82

In [ ]:
submissions_experimento <- submissions[grepl("KA420_", fileName)]
cat("Total de submissions del experimento:", nrow(submissions_experimento), "\n")

submissions_experimento[, origen := ifelse(grepl("KA420_combo", fileName), "local", "colab")]
submissions_experimento[, id := as.integer(gsub(".*id=([0-9]+).*", "\\1", description))]
submissions_experimento[, publicScore := as.numeric(publicScore)]

submissions_validas <- submissions_experimento[!is.na(id)]
cat("Con id valido:", nrow(submissions_validas), "\n")
cat("IDs duplicados:", sum(duplicated(submissions_validas$id)), "\n")

Total de submissions del experimento: 75

Warning message in eval(jsub, SDenv, parent.frame()):
“NAs introduced by coercion”

Con id valido: 64
IDs duplicados: 0

In [ ]:
if (sum(duplicated(submissions_validas$id)) > 0) {
  ids_repetidos <- submissions_validas[duplicated(id) | duplicated(id, fromLast = TRUE)][order(id)]
  print(ids_repetidos[, list(id, fileName, date, publicScore, status)])
}

In [ ]:
grilla_hiperparams <- readRDS("grilla_hiperparams.RDS")

resultados_kaggle <- merge(
  grilla_hiperparams,
  submissions_validas[, list(id, publicScore, status, date, origen)],
  by = "id",
  all.x = TRUE
)

resultados_kaggle <- resultados_kaggle[order(-publicScore)]
fwrite(resultados_kaggle, "resultados_kaggle_completo.csv")

print(resultados_kaggle[1:15])
cat("\nCon score valido:", sum(!is.na(resultados_kaggle$publicScore)),
    "de", nrow(resultados_kaggle), "combinaciones totales de la grilla\n")

       id feature_fraction minsplit minbucket maxdepth    cp    estado
    <int>            <num>    <num>     <num>    <num> <num>    <char>
 1:    63              0.5      500       100        8    -1 pendiente
 2:    50              0.5      400       100        7    -1    subido
 3:    51              0.5      400       100        8    -1    subido
 4:    49              0.5      400       100        6    -1    subido
 5:    62              0.5      500       100        7    -1 pendiente
 6:    61              0.5      500       100        6    -1    subido
 7:    64              0.5      500       150        6    -1 pendiente
 8:    45              0.3      700       175        8    -1    subido
 9:    58              0.5      400       200        6    -1    subido
10:    60              0.5      400       200        8    -1    subido
11:    55              0.5      400       175        6    -1    subido
12:    52              0.5      400       150        6    -1    subido
13:    27              0.3      600       100        8    -1    subido
14:    59              0.5      400       200        7    -1    subido
15:    39              0.3      700       100        8    -1    subido
    publicScore                    status                date origen
          <num>                    <char>              <POSc> <char>
 1:     357.081 SubmissionStatus.COMPLETE 2026-08-24 02:37:54  local
 2:     353.331 SubmissionStatus.COMPLETE 2026-08-23 21:19:43  colab
 3:     353.081 SubmissionStatus.COMPLETE 2026-08-23 21:48:35  colab
 4:     352.165 SubmissionStatus.COMPLETE 2026-08-23 20:54:28  colab
 5:     351.831 SubmissionStatus.COMPLETE 2026-08-24 02:23:38  local
 6:     351.415 SubmissionStatus.COMPLETE 2026-08-24 02:04:03  colab
 7:     350.831 SubmissionStatus.COMPLETE 2026-08-24 02:48:56  local
 8:     349.915 SubmissionStatus.COMPLETE 2026-08-23 19:46:02  colab
 9:     348.165 SubmissionStatus.COMPLETE 2026-08-24 00:44:30  colab
10:     345.581 SubmissionStatus.COMPLETE 2026-08-24 01:41:43  colab
11:     345.498 SubmissionStatus.COMPLETE 2026-08-23 23:27:25  colab
12:     344.331 SubmissionStatus.COMPLETE 2026-08-23 22:10:10  colab
13:     343.165 SubmissionStatus.COMPLETE 2026-08-23 14:29:51  colab
14:     342.581 SubmissionStatus.COMPLETE 2026-08-24 01:10:56  colab
15:     341.665 SubmissionStatus.COMPLETE 2026-08-23 17:42:39  colab

Con score valido: 64 de 144 combinaciones totales de la grilla



---